### ISSUE TITLE
Template for bluray system icons.

### ISSUE THREAD

**Issue by nonamer66** [RetroHursty69/es-theme-bluray#4]
Thanks RetroHursty69 for all the time you make in designing these cool themes. It really makes the experience very enjoyable. 

Question: I would like to make kid friendly versions of CPII and CPIII and Atari. Also some other ones like 3-4 player. Can you please provide your template?  thank you

**Comment by RetroHursty69** [comment]
Hi

Sadly I have mis-placed the template for the Bluray covers. It probably would not have been much use as the reflection was all manual anyway. If you want to provide me with a list I will see what I can do.

Dwayne
